name = "web-nosuke"
compatibility_date = "2023-06-01"

[build]
command = "npm run build"
output_dir = ".next/static"

[site]
bucket = ".next/static"

[env.production]
routes = [
  { pattern = "/api/*", function = "api" }
]

[functions]
directory = "functions" 