name = "findout-career1"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npx @cloudflare/next-on-pages@1"

[build.environment_variables]
NODE_VERSION = "18"

[[pages]]
project = "findout-career1"
production_branch = "main"
build_output_dir = ".vercel/output/static" 